# This is a basic workflow to help you get started with Actions

name: Hello actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  name: OReilly
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:

    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-verion: '12.x'
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        uses: demurgos/ga-deploy-git@v1
        with:
          accessToken: ${{ secrets.access_token }}
          srcDir: build
          destBranch: gh-pages

weather:
    runs-on: ubuntu-latest
    env:
      location: '28.550,-81.40'
      lang: en
      units: us 
      exclude: 'minutely,hourly,daily, alerts,flags'
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps:
      - name: Current Weather
        run: curl -s --url hhtps://api.darksky.net/forcast

  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"

  pull_request_only:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
